# typed: false
# frozen_string_literal: true

# Generated by packages/aicippy-code/script/publish.ts on every release. Do not edit by hand.
class AicippyCode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://www.aicippy.com"
  version "1.18.51"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://www.aicippy.com/releases/cli/1.18.51/aicippy-code-darwin-x64.zip"
      sha256 "a156b11c24c225147115db18a332ab45a1a51872c788feadf2e5c2b33c5ab345"

      def install
        bin.install "aicippy-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://www.aicippy.com/releases/cli/1.18.51/aicippy-code-darwin-arm64.zip"
      sha256 "cfe96df9cd7e51bd775afe2b4936cdf7dfd6d49e87021ada6cd14094c70109d3"

      def install
        bin.install "aicippy-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://www.aicippy.com/releases/cli/1.18.51/aicippy-code-linux-x64.tar.gz"
      sha256 "e8bb74ee5f2814c2e6635f3665fa2c03b7b673f714b773590959bb01cdf9ba58"
      def install
        bin.install "aicippy-code"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://www.aicippy.com/releases/cli/1.18.51/aicippy-code-linux-arm64.tar.gz"
      sha256 "23a95de9a5770d44390ae75f6f69ee6a5bffd36f72d0cc21495562b9c791151e"
      def install
        bin.install "aicippy-code"
      end
    end
  end
end

